export const categories = {
  "music-collab": "Music Collab",
  "short-stories":"Short Stories",
  "long-stories":"Long Stories",
  "journal":"Journal",
  "showcase":"Showcase",
  "music-share":"Music Share",
  "feedback":"Feedback",
  "looking-for-writers":"Looking For Writers",
  "looking-for-beats":"Looking For Beats",
  "creative-writing":"Creative Writing",
  "incubator":"Incubator",
  "suggestion-box":"Suggestion Box",
  "help":"Help",
  "music-discussion":"Music Discussion",
  "random":"Random",
  "personal":"Personal",
  "testing":"Testing",
}