import Providers from "@/utils/provider";
import React from 'react';
import NavBar from "@/components/navBar";
import './globals.css'



export const metadata = {
  title: 'Message Board v2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
